aws:
  secretsmanager:
    region: ap-northeast-2

app:
  domain: https://www.xxihye.online/

spring:
  config:
    import:
        - aws-secretsmanager:shorturl-db
        - aws-secretsmanager:shorturl-jwt

  datasource:
    username: ${username}
    password: ${password}
    url: ${jdbc_url}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${secret}
  access-expiration: ${access-expiration}
  refresh-expiration: ${refresh-expiration}